users:
  authelia:
    displayname: "Authelia"
    password: "$6$rounds=500000$jD2.rQYwQ/bJ9e/R$B8p1qgJb.K0JbJ.r9e/R.K0JbJ.rQYwQ/bJ9e/R.K0JbJ.rQYwQ/bJ9e/R.K0JbJ.rQYwQ/bJ9e/R."
    email: authelia@example.com
    groups:
      - admins
      - dev
