services:
  ts-uptime-kuma:
    image: tailscale/tailscale:latest
    container_name: ts-uptime-kuma
    hostname: uptime-kuma
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--accept-dns=false
    volumes:
      - ../../data/tailscale/uptime-kuma:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - lab_network

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    network_mode: service:ts-uptime-kuma
    volumes:
      - ../../data/uptime-kuma:/app/data
    depends_on:
      - ts-uptime-kuma

  ts-dockge:
    image: tailscale/tailscale:latest
    container_name: ts-dockge
    hostname: dockge
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--accept-dns=false
    volumes:
      - ../../data/tailscale/dockge:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - lab_network

  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    container_name: dockge
    network_mode: service:ts-dockge
    environment:
      - DOCKGE_STACKS_DIR=/lab/docker/cloudlab/compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../data/dockge:/app/data
      - ../../compose:/lab/docker/cloudlab/compose
    depends_on:
      - ts-dockge

networks:
  lab_network:
    external: true
